port: 8080
token:
  key: "?E(H+MbQeThWmZq4t6w9z$C&F)J@NcRf"
  validDays: 30
mongodb:
  uri: "mongodb://localhost:27017"
  database: "todo"
goCq:
  uri: "http://localhost:5700"
  websocketUri: "ws://localhost:8080"
  type: "ws"
